# Generated by Django 5.1 on 2024-08-24 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('JobListings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('in_review', 'In Review'), ('rejected', 'Rejected'), ('accepted', 'Accepted')], max_length=50)),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('cover_letter', models.TextField()),
                ('resume', models.FileField(upload_to='Files')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobListings.jobmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
