# Generated by Django 5.1 on 2024-08-26 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationAndTracking', '0002_notificationmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationmodel',
            name='application_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='applicationAndTracking.applicationmodel'),
            preserve_default=False,
        ),
    ]
